packages:
  - 'packages/*'
  - 'actions/*'
allowBuilds:
  esbuild: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@cpdevtools/ts-dev-utilities'
  - '@sinclair/typebox'
  - 'node-releases'
  - 'terser'
  - '@cpdevtools/ts-dev-utilities-cli@1.1.3'
  - '@cpdevtools/ts-dev-utilities-cli@1.1.5'
