name: Create Release PR

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    uses: ./.github/workflows/create-release-pr.yml
    with:
      branch: ${{ github.ref_name }}
      versions-file: '.github/versions.yml'
    secrets: inherit